config/routes.rb
Mintyquinty::Application.routes.draw do
	root :controller => 'static', :action => '/'
  
  # top
  match "/mintyreddit" => "reddit_views#index"
  
  # saved
  match "/myreddit" => "reddit_views#saved"
  
  # oauth2 routes
  match "/auth/reddit/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

end

app/models/reddit_content.rb
class RedditContent < ActiveRecord::Base
  include HTTParty

  def self.get_top current_user, params
    headers = { "Authorization" => "Bearer #{current_user.token}", "User-Agent" => "web.com.mintyquinty.mintyreddit:v0.0.9 (by /u/mintyquinty)" } if current_user
    top_url = current_user ? "https://oauth.reddit.com/top.json" : "https://www.reddit.com/top.json"
    query = { "count" => 25, "raw_json" => 1 }
    query[:after] = params['after'] if params['after']
    query[:before] = params['before'] if params['before']
    payload = get(top_url, :query => query, :headers => headers)
    if payload.success?
      payload
    else
      raise payload.response  
    end
  end
  
  def self.get_saved current_user, params
    headers = { "Authorization" => "Bearer #{current_user.token}", "User-Agent" => "web.com.mintyquinty.mintyreddit:v0.0.9 (by /u/mintyquinty)" }
    query = { "count" => 25, "raw_json" => 1 }
    query[:after] = params['after'] if params['after']
    query[:before] = params['before'] if params['before']
    payload = get("https://oauth.reddit.com/user/#{current_user.name}/saved.json", :query => query, :headers => headers)
    if payload.success?
      payload
    else
      raise payload.response  
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :uid
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    if @current_user && Time.at(@current_user.token_expires_at) > Time.now
      @current_user
    else
      nil
    end
    
  end

end

app/controllers/reddit_views_controller.rb
class RedditViewsController < ApplicationController
  
  def index
    @top = RedditContent.get_top current_user, params
    
    respond_to do |format|
      format.html # index.html.erb
      format.json
    end
  end
  
  def saved
    if current_user
      @saved = RedditContent.get_saved current_user, params
    
      respond_to do |format|
        format.html
        format.json
      end
    else
      redirect_to mintyreddit_path, :notice => "You need to sign into reddit first."
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id

    token = auth['credentials']['token']
    token_expires_at = auth['credentials']['expires_at']
    user.token = token
    user.token_expires_at = token_expires_at
    user.save!
    
    redirect_to mintyreddit_path, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to mintyreddit_path, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reddit_views_helper.rb
module RedditViewsHelper
  
  def get_image_source path
    src = 'mintyreddit.png'
    case path
    when 'nsfw'
      src = 'mintyreddit_nsfw.png'
    when 'self'
      src = 'mintyreddit.png'
    when ''
      src = 'mintyreddit.png'
    else
      src = path
    end
    src
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mintyquinty</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= yield :javascript %>

</body>
</html>

app/views/reddit_views/_header.html.erb
<header>
	<% if current_user %>
	  <%= link_to "Sign Out", signout_path, class: 'action-link' %>
	  <h4><%= current_user.name.upcase %></h4>
	  
	  <div class="tabs">
		<a href="/mintyreddit">top</a>
		<a href="/myreddit">saved</a>
	  </div>
	  
	<% else %>
	  <%= link_to "Sign in to reddit", "/auth/reddit", class: 'action-link' %>
	<% end %>
</header>

app/views/reddit_views/index.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>">
  <%= value %>
</div>
<% end %>

<%= render 'reddit_views/header' %>

<table class="table table-striped table-hover">
	<tbody>
	<% @top['data']['children'].each_with_index do |thing, i| %>
		<tr>
			<td class="count"><%= i + 1 %></td>
			<td>
				<a href="http://www.reddit.com/<%= thing['data']['permalink'] %>" target="_new">
					<%= image_tag (get_image_source thing['data']['thumbnail']), width: 70 %>
				</a>
			</td>
			<td class="info">
				<a href="http://www.reddit.com/<%= thing['data']['permalink'] %>" target="_new" class="title"><%= thing['data']['title'] %></a>
				<span>(<%= thing['data']['domain'] %>)</span>

				<% if current_user %>
					<div class="save-me-box">
						<a href="#" class="save-me" data-kind="<%= thing['kind'] %>" data-id="<%= thing['data']['id'] %>" data-category="<%= thing['data']['subreddit'] %>"><%= thing['data']['saved'] ? 'unsave' : 'save' %></a>
					</div>
				<% end %>
			</td>
		</tr>
	<% end %>
	</tbody>
</table>

<div class="before-and-after">
	<% if @top['data']['before'] %>
		<a href="/mintyreddit?before=<%= @top['data']['before'] %>">&laquo; Prev</a>
	<% end %>
	<% if @top['data']['after'] %>
		<a href="/mintyreddit?after=<%= @top['data']['after'] %>">Next &raquo;</a>
	<% end %>
</div>

<% if current_user %>
	<% provide :javascript do %>
	  <%= javascript_tag do %>
	    $(function() {
	    	var view = new app.views.reddit.RedditContentsView({ el: 'body', 'token': '<%= current_user.token %>' });
	    });
	  <% end %>
	<% end %>
<% end %>

app/views/reddit_views/saved.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>">
  <%= value %>
</div>
<% end %>

<%= render 'reddit_views/header' %>

<table class="table table-striped table-hover">
	<tbody>
	<% @saved['data']['children'].each_with_index do |thing, i| %>
		<tr>
			<td class="count"><%= i + 1 %></td>
			<td>
				<a href="http://www.reddit.com/<%= thing['data']['permalink'] %>" target="_new">
					<%= image_tag (get_image_source thing['data']['thumbnail']), width: 70 %>
				</a>
			</td>
			<td class="info">
				<a href="http://www.reddit.com/<%= thing['data']['permalink'] %>" target="_new" class="title"><%= thing['data']['title'] %></a>
				<span>(<%= thing['data']['domain'] %>)</span>
			</td>
		</tr>
	<% end %>
	</tbody>
</table>

<div class="before-and-after">
	<% if @saved['data']['before'] %>
		<a href="/myreddit?before=<%= @saved['data']['before'] %>">&laquo; Prev</a>
	<% end %>
	<% if @saved['data']['after'] %>
		<a href="/myreddit?after=<%= @saved['data']['after'] %>">Next &raquo;</a>
	<% end %>
</div>